sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.3

before_install:
  - export PATH=/opt/ghc/7.10.3/bin:$PATH
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --no-terminal --skip-ghc-check test
